jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7
spring:
  #数据库相关配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #这里加上后缀用来防止mysql乱码,serverTimezone=GMT%2b8设置时区ENC()是固定写法
    url: ENC(5LgivIIO45sMSbNi369lvFw+QJ7m87P1gWRrbdzlzPtVPBnA2JSDIbXsCaZGlCDlmfGd2mN2BFe1k5CFBKSSeYLf9L59qBKX0r/qd8PkZoKIKqpv4Qnh4+dS/MbmZ60SP8SqwzEZzcc=)
    username: ENC(x496f7liyU1UXDcZZOXM1g==)
    password: ENC(ze6P1C9FCfFUUoNX64JR0w==)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  #返回的api接口的配置，全局有效
  jackson:
    default-property-inclusion: non_null #如果某一个字段为null，就不再返回这个字段

server:
  port: 8083
