#加密配置文件
jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7
spring:
  #数据库相关配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #这里加上后缀用来防止mysql乱码,serverTimezone=GMT%2b8设置时区ENC()是固定写法
    url: ENC(5LgivIIO45sMSbNi369lvFw+QJ7m87P1gWRrbdzlzPtVPBnA2JSDIbXsCaZGlCDlmfGd2mN2BFe1k5CFBKSSeYLf9L59qBKX0r/qd8PkZoKIKqpv4Qnh4+dS/MbmZ60SP8SqwzEZzcc=)
    username: ENC(x496f7liyU1UXDcZZOXM1g==)
    password: ENC(ze6P1C9FCfFUUoNX64JR0w==)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    encoding: utf-8
    mode: HTML5
  mvc:
    static-path-pattern: /**


server:
  port: 8083

servlet:
    session:
      timeout: 60s
