#加密配置文件
jasypt:
  encryptor:
    password: EbfYkitulv73I2p0mXI50JMXoaxZTKJ7
spring:
  #数据库相关配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #这里加上后缀用来防止mysql乱码,serverTimezone=GMT%2b8设置时区ENC()是固定写法
    url: jdbc:mysql://127.0.0.1:3306/codeox?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    username: dqq
    password: dqq
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    encoding: utf-8
    mode: HTML5
  mvc:
    static-path-pattern: /**

server:
  port: 8083

servlet:
    session:
      timeout: 60s
codeox:
  imagePath: /home/dqq/fileUpload/
  admin.name: codeoxadmin
  admin.password: codeoxadmin